version: '3.8'

services:
  postgraphile-nft-metadata-sql:
    container_name: postgraphile-nft-metadata-sql
    image: postgres:14-alpine
    user: postgres
    volumes:
      - postgraphile-nft-metadata-sql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dreamer
    ports:
      - 5432:5432

volumes:
  postgraphile-nft-metadata-sql-data: {}